### ISSUE TITLE
Clarification: Subscripts and Superscripts

### ISSUE THREAD

**Issue by jahewson** [MathML/MathMLinHTML5#28]
First of all, thanks for this fantastic resource! I'm seeking to clarify some of the details of superscripts and subscripts:

- Figure 20 uses `LargeOpItalicCorrection` but Figure 21 uses `ItalicCorrection`, while Figure 22 uses neither but the text says if `largeop="true"` then italic correction actually is used?
- `SuperBottom` is mentioned in the text describing `msup` but does not appear in Figure 21. Instead we have `SuperBottomShift`.
- `SuperscriptBaselineDropMax ` is mentioned in the text describing `msup` but needs a blue background as it's a math constant. Same for the text describing `msubsup`.
- `SubShift ` is mentioned in the text describing `msup` instead of `SuperShift`.
- In  the text describing `msubsup` conditions 3. and 6. are identical. I assume condition 6. is supposed to be describing `SubscriptBaselineDrop` instead?
- Text describing msubsup refers to `SuperBottomShift`, should this be `SuperBottom`?
- I find it quite difficult to see the difference between the red and orange colors, can the contrast between them be increased?
- `SubShift` may be `SuperscriptShiftUpCramped` or `SuperscriptShiftUp` but TeX has a 3rd option,`sub1` vs. `sub2` for display vs. text style, I assume this is a limitation of OpenType Math, but is it worth commenting on?

**Comment by fred-wang** [comment]
@jahewson: Thank you very much for your feedback. As you probably noticed this is still a draft and the document is definitely going to be improved while it is implemented in WebKit/Blink/Edge. For now, it is mostly the interpretation of the MATH table made of Gecko's MathML implementation and I'm not 100% sure about Microsoft's intention... At least, I already fixed the obvious mistakes you reported.

> Figure 20 uses LargeOpItalicCorrection but Figure 21 uses ItalicCorrection, while Figure 22 uses neither but the text says if largeop="true" then italic correction actually is used?

@khaledhosny may give more details, but from what I understood (this is not exactly how it is implemented in Gecko/WebKit):

1) In general, the subscript are positioned at the advance width of the base and the superscript are shifted forward by the italic correction.

2) When the base is a largeop, we do the contrary: the superscript is positioned at the advance width of the base and the subscript is shifted backward by the italic correction.

The figures are a bit confusing because it does not indicate in which case we are. But Figure 21 is in 1), Figure 20 is in 2) and in Figure 22 assumes that the italic correction is 0.

> I find it quite difficult to see the difference between the red and orange colors, can the contrast between them be increased?

Yes, probably it should be improved when the italic correction stuff is clarified. Probably, it will be better to have separate figures for the italic correction.

> SubShift may be SuperscriptShiftUpCramped or SuperscriptShiftUp but TeX has a 3rd option,sub1 vs. sub2 for display vs. text style, I assume this is a limitation of OpenType Math, but is it worth commenting on?

I have to check the TeXBook again but IIRC, this is indeed a limitation (or feature) of the MATH table.

**Comment by khaledhosny** [comment]
I think @fred-wang description is right (there is also math kerning that is applied after the italic correction).

**Comment by fred-wang** [comment]
> I think @fred-wang description is right (there is also math kerning that is applied after the italic correction).

Yes, math kerning is not handled at the moment (issue #11)

**Comment by jahewson** [comment]
Thanks, that helps. One thing which was particularly confusing was this aspect (in bold):

> 2) When the base is a largeop, we do the contrary: **the superscript is positioned at the advance width of the base** and the subscript is shifted backward by the italic correction.

Which does make sense when you think about integrals.
